name: Mbest700-Jar-Uretici
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: gradle build # 'gradlew' yerine direkt 'gradle' kullanıyoruz
        
      - name: Jar-Dosyasini-Ver
        uses: actions/upload-artifact@v4
        with:
          name: Mbest700-Client-1.21.4
          path: build/libs/*.jar
          
